workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    artifacts:
      - build/**/outputs/**/*.ipa
    scripts:
      - name: Build iOS app
        script: |
          # Your build commands go here
          # For example:
          xcodebuild -scheme YourScheme -sdk iphoneos -configuration Release build
